
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class FormDiskon extends javax.swing.JFrame {

    /**
     * Creates new form FormDiskon
     */
    public FormDiskon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHargaAsli = new javax.swing.JLabel();
        lblPersentaseDiskon = new javax.swing.JLabel();
        lblHargaAkhir = new javax.swing.JLabel();
        lblJumlahPenghematan = new javax.swing.JLabel();
        txtHargaAsli = new javax.swing.JTextField();
        txtHargaAkhir = new javax.swing.JTextField();
        txtPenghematan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        comboDiskon = new javax.swing.JComboBox<>();
        txtKupon = new javax.swing.JTextField();
        sliderDiskon = new javax.swing.JSlider();
        lblKodeKupon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRiwayat = new javax.swing.JTextArea();
        lblHemat10 = new javax.swing.JLabel();
        lblHemat25 = new javax.swing.JLabel();
        lblHemat50 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 44, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("️Aplikasi Perhitungan Diskon");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        lblHargaAsli.setForeground(new java.awt.Color(245, 245, 245));
        lblHargaAsli.setText("Harga asli");
        jPanel1.add(lblHargaAsli, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblPersentaseDiskon.setForeground(new java.awt.Color(245, 245, 245));
        lblPersentaseDiskon.setText("Persentase Diskon");
        jPanel1.add(lblPersentaseDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblHargaAkhir.setForeground(new java.awt.Color(245, 245, 245));
        lblHargaAkhir.setText("Harga Akhir");
        jPanel1.add(lblHargaAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblJumlahPenghematan.setForeground(new java.awt.Color(245, 245, 245));
        lblJumlahPenghematan.setText("Jumlah Penghematan");
        jPanel1.add(lblJumlahPenghematan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txtHargaAsli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHargaAsliFocusGained(evt);
            }
        });
        txtHargaAsli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaAsliKeyTyped(evt);
            }
        });
        jPanel1.add(txtHargaAsli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        txtHargaAkhir.setEditable(false);
        jPanel1.add(txtHargaAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, -1));

        txtPenghematan.setEditable(false);
        jPanel1.add(txtPenghematan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 200, -1));

        btnHitung.setBackground(new java.awt.Color(24, 158, 101));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(245, 245, 245));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        btnReset.setBackground(new java.awt.Color(230, 68, 72));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(245, 245, 245));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        comboDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "20%", "30%", "40%", "50%" }));
        comboDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDiskonItemStateChanged(evt);
            }
        });
        jPanel1.add(comboDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));
        jPanel1.add(txtKupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 200, -1));

        sliderDiskon.setForeground(new java.awt.Color(245, 245, 245));
        sliderDiskon.setMajorTickSpacing(10);
        sliderDiskon.setMaximum(50);
        sliderDiskon.setPaintLabels(true);
        sliderDiskon.setPaintTicks(true);
        sliderDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDiskonStateChanged(evt);
            }
        });
        jPanel1.add(sliderDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, -1));

        lblKodeKupon.setForeground(new java.awt.Color(245, 245, 245));
        lblKodeKupon.setText("Kode Kupon");
        jPanel1.add(lblKodeKupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(42, 44, 56));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Riwayat Perhitungan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(245, 245, 245))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        txtAreaRiwayat.setEditable(false);
        txtAreaRiwayat.setColumns(20);
        txtAreaRiwayat.setRows(5);
        jScrollPane1.setViewportView(txtAreaRiwayat);

        jPanel2.add(jScrollPane1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 350, 170));

        lblHemat10.setBackground(new java.awt.Color(241, 196, 15));
        lblHemat10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHemat10.setForeground(new java.awt.Color(0, 0, 0));
        lblHemat10.setText("HEMAT10");
        lblHemat10.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lblHemat10.setOpaque(true);
        jPanel1.add(lblHemat10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblHemat25.setBackground(new java.awt.Color(241, 196, 15));
        lblHemat25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHemat25.setForeground(new java.awt.Color(0, 0, 0));
        lblHemat25.setText("HEMAT25");
        lblHemat25.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lblHemat25.setOpaque(true);
        jPanel1.add(lblHemat25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 70, -1));

        lblHemat50.setBackground(new java.awt.Color(241, 196, 15));
        lblHemat50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHemat50.setForeground(new java.awt.Color(0, 0, 0));
        lblHemat50.setText("PROMO50");
        lblHemat50.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lblHemat50.setOpaque(true);
        jPanel1.add(lblHemat50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed

       try {
        double hargaAsli = Double.parseDouble(txtHargaAsli.getText());
        int diskon = Integer.parseInt(comboDiskon.getSelectedItem().toString().replace("%", ""));
        String kupon = txtKupon.getText().trim().toUpperCase();
        
        // Tambahan diskon dari kupon
        int diskonKupon = 0;
        diskonKupon = switch (kupon) {
               case "HEMAT10" -> 10;
               case "HEMAT25" -> 25;
               case "PROMO50" -> 50;
               default -> 0;
           };

        int totalDiskon = diskon + diskonKupon;
        if (totalDiskon > 80) totalDiskon = 80; // batasi maksimal 80% biar logis

        double hargaAkhir = hargaAsli - (hargaAsli * totalDiskon / 100);
        double penghematan = hargaAsli - hargaAkhir;

        txtHargaAkhir.setText(String.format("%.2f", hargaAkhir));
        txtPenghematan.setText(String.format("%.2f", penghematan));

        // Tambahkan ke riwayat
        txtAreaRiwayat.append("Harga: Rp" + hargaAsli +
                           " | Diskon: " + totalDiskon + "%" +
                           " | Akhir: Rp" + String.format("%.2f", hargaAkhir) + "\n");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk harga!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtHargaAsli.setText("");
        txtKupon.setText("");
        txtHargaAkhir.setText("");
        txtPenghematan.setText("");
        comboDiskon.setSelectedIndex(0);
        sliderDiskon.setValue(0);
        txtAreaRiwayat.setText("");

        // Fokuskan kursor ke kolom harga asli
        txtHargaAsli.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void comboDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDiskonItemStateChanged

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            int diskon = Integer.parseInt(
                comboDiskon.getSelectedItem().toString().replace("%", "")
            );
            sliderDiskon.setValue(diskon);
        }
    }//GEN-LAST:event_comboDiskonItemStateChanged

    private void sliderDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDiskonStateChanged

        int nilai = sliderDiskon.getValue();
        comboDiskon.setSelectedItem(nilai + "%");
    }//GEN-LAST:event_sliderDiskonStateChanged

    private void txtHargaAsliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaAsliKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE && c != java.awt.event.KeyEvent.VK_DELETE) {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtHargaAsliKeyTyped

    private void txtHargaAsliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHargaAsliFocusGained
        txtHargaAsli.setText("");
    }//GEN-LAST:event_txtHargaAsliFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comboDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHargaAkhir;
    private javax.swing.JLabel lblHargaAsli;
    private javax.swing.JLabel lblHemat10;
    private javax.swing.JLabel lblHemat25;
    private javax.swing.JLabel lblHemat50;
    private javax.swing.JLabel lblJumlahPenghematan;
    private javax.swing.JLabel lblKodeKupon;
    private javax.swing.JLabel lblPersentaseDiskon;
    private javax.swing.JSlider sliderDiskon;
    private javax.swing.JTextArea txtAreaRiwayat;
    private javax.swing.JTextField txtHargaAkhir;
    private javax.swing.JTextField txtHargaAsli;
    private javax.swing.JTextField txtKupon;
    private javax.swing.JTextField txtPenghematan;
    // End of variables declaration//GEN-END:variables
}
